sudo: false
dist: trusty

language: node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "node"

script: npm run build &&\
  npm i --no-save webpack@3 extract-text-webpack-plugin && npm run run-test &&\
  npm i --no-save webpack@2 extract-text-webpack-plugin@2 && npm run run-test

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: never
    on_failure: always
