sudo: false
dist: trusty

language: node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "node"

script: npm test && \
  npm --webpackVersion=3.0.0 --extractWebpackVersion=3.0.0 test &&\
  npm --webpackVersion=3 --extractWebpackVersion=3 test

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: never
    on_failure: always
