sudo: false
dist: trusty

language: node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "node"

script: npm test

branches:
  except:
    - gh-pages

jobs:
  include:
    - stage: npm lint
      node_js: "node"
      script: npm run lint

notifications:
  email:
    on_success: never
    on_failure: always
